### ISSUE TITLE
sync

### ISSUE THREAD

**Issue by celesteking** [CpanelInc/scl-php56#1]
Can we get this repo synced to upstream?

**Comment by HoustonDad** [comment]
Hi,
Can you elaborate on what you're needing? PHP 5.6 hasn't been updated in a quite a while, and this source is up to date with the upstream source as far as I can tell.

**Comment by celesteking** [comment]
EA4 supplies 5.6.30-6.6.2, while this one is for 5.6.30-4.

**Comment by HoustonDad** [comment]
@celesteking Yep, you're totally right. Somehow our bamboo CI is not syncing these repos automatically any longer. We'll look into this today, but for now, I've manually synced our repos. This is now updated.
Thanks for the heads up!
